name: Train and Deploy to Hugging Face

on:
  push:
    branches:
      - features/ml-flow

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    env:
      HF_HOME: ${{ github.workspace }}/.cache/huggingface
      HF_TOKEN: ${{ secrets.HF }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_linux.txt
          pip install --upgrade huggingface_hub

      - name: Hugging Face login
        run: |
          huggingface-cli login --token "$HF_TOKEN" --add-to-git-credential

      - name: Create model repo if not exists
        run: |
          huggingface-cli repo create fine-tunning-embeddings --type=model --yes || true

      - name: Train and export models
        run: |
          python fine_tune_ampliado.py

      - name: Upload fine-tuned model
        run: |
          python -c "from huggingface_hub import upload_folder; upload_folder(repo_id='jacgandres/fine-tunning-embeddings', folder_path='fine_tuned_model_oil_gas', path_in_repo='', token='${HF_TOKEN}')"

      - name: Upload ONNX model
        run: |
          python -c "from huggingface_hub import upload_folder; upload_folder(repo_id='jacgandres/fine-tunning-embeddings', folder_path='fine_tuned_model_oil_gas/onnx', path_in_repo='onnx', token='${HF_TOKEN}')"

      - name: Upload final model folders
        run: |
          for d in model/tuned-oil-gas-* model/onnx-oil-gas-int8-*; do
            if [ -d "$d" ]; then
              folder_name=$(basename "$d")
              python -c "from huggingface_hub import upload_folder; upload_folder(repo_id='jacgandres/fine-tunning-embeddings', folder_path='$d', path_in_repo='$folder_name', token='${HF_TOKEN}')"
            fi
          done
